# Generated by Django 5.2.14 on 2026-06-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🔧', max_length=50),
        ),
    ]
