# Generated by Django 5.2.14 on 2026-06-30 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_providerblockeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerblockeddate',
            name='unavailable_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providerblockeddate',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='providerblockeddate',
            name='start_time',
            field=models.DateField(),
        ),
    ]
