# Generated by Django 5.2.14 on 2026-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_providerblockeddate_unavailable_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
