# Generated by Django 5.2.14 on 2026-06-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='is_bestseller',
            new_name='is_bestworker',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='provider',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
