# Generated by Django 5.2.14 on 2026-07-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_is_bestseller_provider_is_bestworker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
