# Generated by Django 5.2.14 on 2026-07-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_provider_phone_provider_provider_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=200)),
                ('work_image', models.ImageField(upload_to='provider_works/')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=15)),
                ('work_address', models.TextField()),
                ('completed_date', models.DateField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='service.provider')),
            ],
        ),
    ]
