# Generated by Django 5.2.14 on 2026-07-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_providerwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='adhaar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
