# Generated by Django 5.2.14 on 2026-07-02 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_provider_adhaar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerwork',
            name='completed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
