# Generated by Django 5.2.14 on 2026-07-03 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_providerwork_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerblockeddate',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.provider'),
        ),
    ]
