# Generated by Django 5.2.14 on 2026-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
