# Generated by Django 5.2.14 on 2026-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_provider_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
