# Generated by Django 5.2.14 on 2026-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
