# Generated by Django 5.2.14 on 2026-07-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_provider_original_price_alter_provider_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
